# Generated by Django 4.2.2 on 2023-06-27 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_title', models.CharField(blank=True, max_length=100)),
                ('sore_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sort_level', models.CharField(blank=True, max_length=50)),
                ('sort_remark', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
                'db_table': 'tb_category',
            },
        ),
    ]
